# Generated by Django 5.1.1 on 2024-10-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notatki', '0002_note_priorytet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='priorytet',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=0),
        ),
    ]
